"""sistem ayarlari tablosu

Revision ID: bb9e08a93abd
Revises: 8f66cdf80ab1
Create Date: 2026-09-21 13:51:30.665497
"""
from alembic import op
import sqlalchemy as sa


revision = 'bb9e08a93abd'
down_revision = '8f66cdf80ab1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('anahtar', sa.String(length=100), nullable=False),
    sa.Column('sifreli_deger', sa.Text(), nullable=False),
    sa.Column('son_dort', sa.String(length=8), nullable=True),
    sa.Column('degistiren_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['degistiren_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anahtar', name='uq_system_setting_anahtar')
    )
    op.create_index(op.f('ix_system_settings_anahtar'), 'system_settings', ['anahtar'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_anahtar'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
