"""Kampanya platform dagilimi

Revision ID: 6b85e61b6196
Revises: 92be8c02f6f9
Create Date: 2026-09-23 18:59:56.073472
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# 'reklam_platformu' YENI bir tur. Tur ACIKCA olusturulur; sutun tanimi
# create_type=False ile onu KULLANIR. Ikisi de olusturmaya calisirsa
# "type already exists" hatasi cikar. Geri alinirken de DUSURULUR; yoksa
# tekrar ileri alindiginda ayni hata verir.
PLATFORM_DEGERLERI = (
    'META', 'GOOGLE_ADS', 'TIKTOK_ADS', 'LINKEDIN_ADS',
    'X_ADS', 'YOUTUBE_ADS', 'ORGANIK',
)
PLATFORM = postgresql.ENUM(
    *PLATFORM_DEGERLERI, name='reklam_platformu', create_type=False
)


revision = '6b85e61b6196'
down_revision = '92be8c02f6f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    postgresql.ENUM(*PLATFORM_DEGERLERI, name='reklam_platformu').create(
        op.get_bind(), checkfirst=True
    )
    op.create_table('campaign_platforms',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('platform', PLATFORM, nullable=False),
    sa.Column('butce', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hedef', sa.String(length=200), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('harici_kimlik', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'platform', name='uq_campaign_platform')
    )
    op.create_index(op.f('ix_campaign_platforms_campaign_id'), 'campaign_platforms', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_platforms_workspace_id'), 'campaign_platforms', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_platforms_workspace_id'), table_name='campaign_platforms')
    op.drop_index(op.f('ix_campaign_platforms_campaign_id'), table_name='campaign_platforms')
    op.drop_table('campaign_platforms')
    postgresql.ENUM(*PLATFORM_DEGERLERI, name='reklam_platformu').drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
