"""Gorunum tercihi: tema ve vurgu

Revision ID: 92be8c02f6f9
Revises: a22e897d4746
Create Date: 2026-09-23 18:46:28.775536
"""
from alembic import op
import sqlalchemy as sa


revision = '92be8c02f6f9'
down_revision = 'a22e897d4746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tema', sa.String(length=10), server_default='sistem', nullable=False))
    op.add_column('users', sa.Column('vurgu', sa.String(length=20), server_default='mavi', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vurgu')
    op.drop_column('users', 'tema')
    # ### end Alembic commands ###
