"""Makine kimliginde "tum musteriler" kapsami

True ise sonradan eklenen musteriler de otomatik kapsama girer; her yeni
musteri icin elle yetki verilmesi gerekmez.

Revision ID: a820134d6a39
Revises: a1b0035c2881
Create Date: 2026-09-21 19:07:29.488341
"""
from alembic import op
import sqlalchemy as sa


revision = 'a820134d6a39'
down_revision = 'a1b0035c2881'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default ZORUNLU: uretimde bu tabloda zaten satir var ve
    # varsayilansiz NOT NULL bir sutun eklenemez. Test veritabani bos
    # oldugu icin bu, migration uretilirken gorunmuyordu.
    op.add_column(
        'api_clients',
        sa.Column(
            'all_workspaces', sa.Boolean(),
            nullable=False, server_default=sa.false(),
        ),
    )
    # Varsayilan yalnizca mevcut satirlar icindi; bundan sonrasini
    # uygulama belirlesin diye kaldiriliyor.
    op.alter_column('api_clients', 'all_workspaces', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_clients', 'all_workspaces')
    # ### end Alembic commands ###
