"""Rol bazli izin ozellestirmeleri

Her musteri icin her rolun hangi izne sahip oldugu. YALNIZCA varsayilandan
farkli olanlar saklanir

Revision ID: 61b105d2573f
Revises: a820134d6a39
Create Date: 2026-09-23 13:18:52.057606
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '61b105d2573f'
down_revision = 'a820134d6a39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_grants',
    # create_type=False ZORUNLU: 'workspace_role' turu zaten var
    # (workspace_members tablosuyla olusmustu). Tekrar olusturmaya
    # calismak "tur zaten var" hatasi verir.
    sa.Column(
        'role',
        postgresql.ENUM(
            'OWNER', 'ADMIN', 'STRATEGIST', 'EDITOR', 'VIEWER',
            name='workspace_role', create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('permission', sa.String(length=60), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'role', 'permission', name='uq_role_grant')
    )
    op.create_index(op.f('ix_role_grants_permission'), 'role_grants', ['permission'], unique=False)
    op.create_index(op.f('ix_role_grants_role'), 'role_grants', ['role'], unique=False)
    op.create_index(op.f('ix_role_grants_workspace_id'), 'role_grants', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_grants_workspace_id'), table_name='role_grants')
    op.drop_index(op.f('ix_role_grants_role'), table_name='role_grants')
    op.drop_index(op.f('ix_role_grants_permission'), table_name='role_grants')
    op.drop_table('role_grants')
    # ### end Alembic commands ###
