"""Izlenen hesaplar

Revision ID: 5489175ca0e3
Revises: ccd07a5a0fbc
Create Date: 2026-09-23 14:26:23.438954
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# 'platform' turu ZATEN VAR (social_accounts ile olusmustu). create_type=False
# olmadan "type already exists" hatasi verir.
PLATFORM = postgresql.ENUM(
    'INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'YOUTUBE', 'LINKEDIN', 'X', 'PINTEREST',
    name='platform', create_type=False,
)
# 'izleme_turu' YENI. Tur ACIKCA olusturulur; sutun tanimi create_type=False
# ile onu KULLANIR. Ikisi de olusturmaya calisirsa "zaten var" hatasi cikar.
IZLEME_DEGERLERI = ('KENDI', 'RAKIP', 'REFERANS')
IZLEME_TURU = postgresql.ENUM(*IZLEME_DEGERLERI, name='izleme_turu', create_type=False)


revision = '5489175ca0e3'
down_revision = 'ccd07a5a0fbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    postgresql.ENUM(*IZLEME_DEGERLERI, name='izleme_turu').create(
        op.get_bind(), checkfirst=True
    )
    op.create_table('tracked_accounts',
    sa.Column('platform', PLATFORM, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('tur', IZLEME_TURU, nullable=False),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('veri_durumu', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'platform', 'username', name='uq_tracked_account')
    )
    op.create_index(op.f('ix_tracked_accounts_workspace_id'), 'tracked_accounts', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_accounts_workspace_id'), table_name='tracked_accounts')
    op.drop_table('tracked_accounts')
    # Tur birakilirsa, tekrar ileri alindiginda "zaten var" hatasi verir.
    postgresql.ENUM(*IZLEME_DEGERLERI, name='izleme_turu').drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
