"""kullanici_workspace_ve_tum_tablolar

Revision ID: 8f66cdf80ab1
Revises: 0e3730394f1f
Create Date: 2026-09-20 16:59:29.590612
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8f66cdf80ab1'
down_revision = '0e3730394f1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ai_monthly_budget_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('ai_tasks',
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='ai_task_status'), nullable=False),
    sa.Column('provider', sa.Enum('CLAUDE', 'MANUS', 'GEMINI', 'FAKE', name='ai_provider'), nullable=False),
    sa.Column('external_task_id', sa.String(length=200), nullable=True),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tasks_external_task_id'), 'ai_tasks', ['external_task_id'], unique=False)
    op.create_index(op.f('ix_ai_tasks_task_type'), 'ai_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_tasks_workspace_id'), 'ai_tasks', ['workspace_id'], unique=False)
    op.create_table('approvals',
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'INTERNAL_REVIEW', 'CLIENT_REVIEW', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='content_status'), nullable=False),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_subject_id'), 'approvals', ['subject_id'], unique=False)
    op.create_index(op.f('ix_approvals_subject_type'), 'approvals', ['subject_type'], unique=False)
    op.create_index(op.f('ix_approvals_workspace_id'), 'approvals', ['workspace_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('brands',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_workspace_id'), 'brands', ['workspace_id'], unique=False)
    op.create_table('competitor_accounts',
    sa.Column('platform', sa.Enum('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'YOUTUBE', 'LINKEDIN', 'X', 'PINTEREST', name='platform'), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_accounts_workspace_id'), 'competitor_accounts', ['workspace_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    op.create_table('reports',
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='report_period'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'INTERNAL_REVIEW', 'CLIENT_REVIEW', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='content_status'), nullable=False),
    sa.Column('data_quality_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'period', 'period_start', name='uq_report_period')
    )
    op.create_index(op.f('ix_reports_workspace_id'), 'reports', ['workspace_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('platform', sa.Enum('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'YOUTUBE', 'LINKEDIN', 'X', 'PINTEREST', name='platform'), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('is_professional', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'platform', 'external_id', name='uq_social_account')
    )
    op.create_index(op.f('ix_social_accounts_workspace_id'), 'social_accounts', ['workspace_id'], unique=False)
    op.create_table('system_errors',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_errors_error_code'), 'system_errors', ['error_code'], unique=False)
    op.create_index(op.f('ix_system_errors_occurred_at'), 'system_errors', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_system_errors_workspace_id'), 'system_errors', ['workspace_id'], unique=False)
    op.create_table('trend_observations',
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'YOUTUBE', 'LINKEDIN', 'X', 'PINTEREST', name='platform'), nullable=True),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('relevance_to_brand', sa.Text(), nullable=True),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_task_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_observations_workspace_id'), 'trend_observations', ['workspace_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_event_id', sa.String(length=200), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_event_id', name='uq_webhook_event')
    )
    op.create_index(op.f('ix_webhooks_provider'), 'webhooks', ['provider'], unique=False)
    op.create_index(op.f('ix_webhooks_workspace_id'), 'webhooks', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'STRATEGIST', 'EDITOR', 'VIEWER', name='workspace_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('account_metrics',
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'YOUTUBE', 'LINKEDIN', 'X', 'PINTEREST', name='platform'), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('measurement_period', sa.String(length=50), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_endpoint', sa.String(length=500), nullable=True),
    sa.Column('follower_count', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'social_account_id', 'metric_name', 'measurement_period', 'measured_at', name='uq_account_metric')
    )
    op.create_index(op.f('ix_account_metrics_social_account_id'), 'account_metrics', ['social_account_id'], unique=False)
    op.create_index(op.f('ix_account_metrics_workspace_id'), 'account_metrics', ['workspace_id'], unique=False)
    op.create_table('ai_runs',
    sa.Column('ai_task_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('CLAUDE', 'MANUS', 'GEMINI', 'FAKE', name='ai_provider'), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='ai_task_status'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_task_id'], ['ai_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_ai_task_id'), 'ai_runs', ['ai_task_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_output_hash'), 'ai_runs', ['output_hash'], unique=False)
    op.create_index(op.f('ix_ai_runs_workspace_id'), 'ai_runs', ['workspace_id'], unique=False)
    op.create_table('brand_guidelines',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('tone_of_voice', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('forbidden_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kpi_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_guidelines_brand_id'), 'brand_guidelines', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_guidelines_workspace_id'), 'brand_guidelines', ['workspace_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'INTERNAL_REVIEW', 'CLIENT_REVIEW', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='content_status'), nullable=False),
    sa.Column('kpi_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_brand_id'), 'campaigns', ['brand_id'], unique=False)
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_table('competitor_observations',
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_observations_competitor_id'), 'competitor_observations', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_competitor_observations_workspace_id'), 'competitor_observations', ['workspace_id'], unique=False)
    op.create_table('oauth_credentials',
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_credentials_social_account_id'), 'oauth_credentials', ['social_account_id'], unique=True)
    op.create_index(op.f('ix_oauth_credentials_workspace_id'), 'oauth_credentials', ['workspace_id'], unique=False)
    op.create_table('platform_media',
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'YOUTUBE', 'LINKEDIN', 'X', 'PINTEREST', name='platform'), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'CAROUSEL', 'REEL', 'STORY', 'SHORT', 'TEXT', 'OTHER', name='media_type'), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('permalink', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'platform', 'external_id', name='uq_platform_media')
    )
    op.create_index('ix_media_published', 'platform_media', ['workspace_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_platform_media_social_account_id'), 'platform_media', ['social_account_id'], unique=False)
    op.create_index(op.f('ix_platform_media_workspace_id'), 'platform_media', ['workspace_id'], unique=False)
    op.create_table('report_sections',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_sections_report_id'), 'report_sections', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_sections_workspace_id'), 'report_sections', ['workspace_id'], unique=False)
    op.create_table('ai_cost_events',
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('CLAUDE', 'MANUS', 'GEMINI', 'FAKE', name='ai_provider'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_cost_events_occurred_at'), 'ai_cost_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_ai_cost_events_workspace_id'), 'ai_cost_events', ['workspace_id'], unique=False)
    op.create_table('content_ideas',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('target_metric', sa.String(length=100), nullable=True),
    sa.Column('audience_problem', sa.Text(), nullable=True),
    sa.Column('reason_for_recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'INTERNAL_REVIEW', 'CLIENT_REVIEW', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='content_status'), nullable=False),
    sa.Column('idea_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'idea_fingerprint', name='uq_idea_fingerprint')
    )
    op.create_index(op.f('ix_content_ideas_brand_id'), 'content_ideas', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_idea_fingerprint'), 'content_ideas', ['idea_fingerprint'], unique=False)
    op.create_index(op.f('ix_content_ideas_workspace_id'), 'content_ideas', ['workspace_id'], unique=False)
    op.create_table('media_metrics_raw',
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'YOUTUBE', 'LINKEDIN', 'X', 'PINTEREST', name='platform'), nullable=False),
    sa.Column('source_endpoint', sa.String(length=500), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['platform_media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_metrics_raw_media_id'), 'media_metrics_raw', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_metrics_raw_payload_hash'), 'media_metrics_raw', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_media_metrics_raw_workspace_id'), 'media_metrics_raw', ['workspace_id'], unique=False)
    op.create_index('ix_raw_fetch', 'media_metrics_raw', ['workspace_id', 'fetched_at'], unique=False)
    op.create_table('content_scripts',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'YOUTUBE', 'LINKEDIN', 'X', 'PINTEREST', name='platform'), nullable=False),
    sa.Column('format', sa.Enum('IMAGE', 'VIDEO', 'CAROUSEL', 'REEL', 'STORY', 'SHORT', 'TEXT', 'OTHER', name='media_type'), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('scene_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spoken_script', sa.Text(), nullable=True),
    sa.Column('on_screen_text', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visual_production_brief', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('alternative_hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('production_difficulty', sa.String(length=50), nullable=True),
    sa.Column('brand_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claims_to_verify', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'INTERNAL_REVIEW', 'CLIENT_REVIEW', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='content_status'), nullable=False),
    sa.Column('human_approval_required', sa.Boolean(), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_scripts_idea_id'), 'content_scripts', ['idea_id'], unique=False)
    op.create_index(op.f('ix_content_scripts_workspace_id'), 'content_scripts', ['workspace_id'], unique=False)
    op.create_table('media_metrics_normalized',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('raw_reference_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'YOUTUBE', 'LINKEDIN', 'X', 'PINTEREST', name='platform'), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('measurement_period', sa.String(length=50), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['platform_media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_reference_id'], ['media_metrics_raw.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'media_id', 'metric_name', 'measurement_period', 'measured_at', name='uq_normalized_metric')
    )
    op.create_index(op.f('ix_media_metrics_normalized_media_id'), 'media_metrics_normalized', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_metrics_normalized_workspace_id'), 'media_metrics_normalized', ['workspace_id'], unique=False)
    op.create_table('content_calendar',
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'INTERNAL_REVIEW', 'CLIENT_REVIEW', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='content_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['content_scripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_calendar_script_id'), 'content_calendar', ['script_id'], unique=False)
    op.create_index(op.f('ix_content_calendar_workspace_id'), 'content_calendar', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_calendar_workspace_id'), table_name='content_calendar')
    op.drop_index(op.f('ix_content_calendar_script_id'), table_name='content_calendar')
    op.drop_table('content_calendar')
    op.drop_index(op.f('ix_media_metrics_normalized_workspace_id'), table_name='media_metrics_normalized')
    op.drop_index(op.f('ix_media_metrics_normalized_media_id'), table_name='media_metrics_normalized')
    op.drop_table('media_metrics_normalized')
    op.drop_index(op.f('ix_content_scripts_workspace_id'), table_name='content_scripts')
    op.drop_index(op.f('ix_content_scripts_idea_id'), table_name='content_scripts')
    op.drop_table('content_scripts')
    op.drop_index('ix_raw_fetch', table_name='media_metrics_raw')
    op.drop_index(op.f('ix_media_metrics_raw_workspace_id'), table_name='media_metrics_raw')
    op.drop_index(op.f('ix_media_metrics_raw_payload_hash'), table_name='media_metrics_raw')
    op.drop_index(op.f('ix_media_metrics_raw_media_id'), table_name='media_metrics_raw')
    op.drop_table('media_metrics_raw')
    op.drop_index(op.f('ix_content_ideas_workspace_id'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_idea_fingerprint'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_brand_id'), table_name='content_ideas')
    op.drop_table('content_ideas')
    op.drop_index(op.f('ix_ai_cost_events_workspace_id'), table_name='ai_cost_events')
    op.drop_index(op.f('ix_ai_cost_events_occurred_at'), table_name='ai_cost_events')
    op.drop_table('ai_cost_events')
    op.drop_index(op.f('ix_report_sections_workspace_id'), table_name='report_sections')
    op.drop_index(op.f('ix_report_sections_report_id'), table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index(op.f('ix_platform_media_workspace_id'), table_name='platform_media')
    op.drop_index(op.f('ix_platform_media_social_account_id'), table_name='platform_media')
    op.drop_index('ix_media_published', table_name='platform_media')
    op.drop_table('platform_media')
    op.drop_index(op.f('ix_oauth_credentials_workspace_id'), table_name='oauth_credentials')
    op.drop_index(op.f('ix_oauth_credentials_social_account_id'), table_name='oauth_credentials')
    op.drop_table('oauth_credentials')
    op.drop_index(op.f('ix_competitor_observations_workspace_id'), table_name='competitor_observations')
    op.drop_index(op.f('ix_competitor_observations_competitor_id'), table_name='competitor_observations')
    op.drop_table('competitor_observations')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_brand_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_brand_guidelines_workspace_id'), table_name='brand_guidelines')
    op.drop_index(op.f('ix_brand_guidelines_brand_id'), table_name='brand_guidelines')
    op.drop_table('brand_guidelines')
    op.drop_index(op.f('ix_ai_runs_workspace_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_output_hash'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_ai_task_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_account_metrics_workspace_id'), table_name='account_metrics')
    op.drop_index(op.f('ix_account_metrics_social_account_id'), table_name='account_metrics')
    op.drop_table('account_metrics')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_webhooks_workspace_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_provider'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_trend_observations_workspace_id'), table_name='trend_observations')
    op.drop_table('trend_observations')
    op.drop_index(op.f('ix_system_errors_workspace_id'), table_name='system_errors')
    op.drop_index(op.f('ix_system_errors_occurred_at'), table_name='system_errors')
    op.drop_index(op.f('ix_system_errors_error_code'), table_name='system_errors')
    op.drop_table('system_errors')
    op.drop_index(op.f('ix_social_accounts_workspace_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_reports_workspace_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_competitor_accounts_workspace_id'), table_name='competitor_accounts')
    op.drop_table('competitor_accounts')
    op.drop_index(op.f('ix_brands_workspace_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approvals_workspace_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_subject_type'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_subject_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_ai_tasks_workspace_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_task_type'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_external_task_id'), table_name='ai_tasks')
    op.drop_table('ai_tasks')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
