"""Makine kimligi (n8n) ve otomasyon tablolari

n8n bir insan hesabi kullanmaz: kendi makine kimligi vardir, kapsami
api_client_workspaces ile sinirlidir ve her calismasi automation_runs'a
yazilir.

Revision ID: a1b0035c2881
Revises: 4c1d6a2f9b30
Create Date: 2026-09-21 18:23:29.178941
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a1b0035c2881'
down_revision = '4c1d6a2f9b30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_clients_key_prefix'), 'api_clients', ['key_prefix'], unique=True)
    op.create_table('automation_settings',
    sa.Column('workflow_key', sa.String(length=60), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'workflow_key', name='uq_automation_setting')
    )
    op.create_index(op.f('ix_automation_settings_workflow_key'), 'automation_settings', ['workflow_key'], unique=False)
    op.create_index(op.f('ix_automation_settings_workspace_id'), 'automation_settings', ['workspace_id'], unique=False)
    op.create_table('api_client_workspaces',
    sa.Column('api_client_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_client_id'], ['api_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_client_id', 'workspace_id', name='uq_api_client_workspace')
    )
    op.create_index(op.f('ix_api_client_workspaces_api_client_id'), 'api_client_workspaces', ['api_client_id'], unique=False)
    op.create_index(op.f('ix_api_client_workspaces_workspace_id'), 'api_client_workspaces', ['workspace_id'], unique=False)
    op.create_table('automation_runs',
    sa.Column('workflow_key', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', name='automation_status'), nullable=False),
    sa.Column('trigger', sa.Enum('SCHEDULE', 'MANUAL', name='automation_trigger'), nullable=False),
    sa.Column('external_execution_id', sa.String(length=100), nullable=True),
    sa.Column('api_client_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_client_id'], ['api_clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_runs_external_execution_id'), 'automation_runs', ['external_execution_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_started_at'), 'automation_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_automation_runs_status'), 'automation_runs', ['status'], unique=False)
    op.create_index(op.f('ix_automation_runs_workflow_key'), 'automation_runs', ['workflow_key'], unique=False)
    op.create_index(op.f('ix_automation_runs_workspace_id'), 'automation_runs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_runs_workspace_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_workflow_key'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_status'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_started_at'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_external_execution_id'), table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index(op.f('ix_api_client_workspaces_workspace_id'), table_name='api_client_workspaces')
    op.drop_index(op.f('ix_api_client_workspaces_api_client_id'), table_name='api_client_workspaces')
    op.drop_table('api_client_workspaces')
    op.drop_index(op.f('ix_automation_settings_workspace_id'), table_name='automation_settings')
    op.drop_index(op.f('ix_automation_settings_workflow_key'), table_name='automation_settings')
    op.drop_table('automation_settings')
    op.drop_index(op.f('ix_api_clients_key_prefix'), table_name='api_clients')
    op.drop_table('api_clients')
    # ### end Alembic commands ###

    # Tablolarla birlikte olusturulan enum turleri de silinir. Aksi halde
    # geri alip tekrar ileri almak "tur zaten var" hatasi verir.
    sa.Enum(name='automation_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='automation_trigger').drop(op.get_bind(), checkfirst=True)
